In [1]:
import torch
from torch import nn
from torch.autograd import Variable
from torch import *

In [2]:
torch.int32

torch.int32

In [3]:
a = torch.ones((3,5,2,2))
b = torch.arange(3*5*2*2).view((3,5,2,2))
print b[0,0]
c = b.view((3,5,4));
d = c.permute(0,2,1)
# print c
print d.shape
a = torch.mean(d, 1)
print a.shape
f = a.unsqueeze(1);
(n,_,_) = f.shape
print n
# print d.contiguous().view((12, 5)).shape

print nn.Softmax
softmax = nn.Softmax()
print softmax(f);

tensor([[ 0.,  1.],
        [ 2.,  3.]])
torch.Size([3, 4, 5])
torch.Size([3, 5])
3
<class 'torch.nn.modules.activation.Softmax'>
tensor([[[ 4.2484e-18,  4.2484e-18,  4.2484e-18,  4.2484e-18,  4.2484e-18]],

        [[ 2.0612e-09,  2.0612e-09,  2.0612e-09,  2.0612e-09,  2.0612e-09]],

        [[ 1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00]]])


/Users/nsimsiri/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:17: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.


In [4]:
a = torch.arange(2*3*4).view((2,3,4))
b = torch.Tensor(([[1,1,1],[2,2,2]]));

print a
print b
print b.unsqueeze(2)


tensor([[[  0.,   1.,   2.,   3.],
         [  4.,   5.,   6.,   7.],
         [  8.,   9.,  10.,  11.]],

        [[ 12.,  13.,  14.,  15.],
         [ 16.,  17.,  18.,  19.],
         [ 20.,  21.,  22.,  23.]]])
tensor([[ 1.,  1.,  1.],
        [ 2.,  2.,  2.]])
tensor([[[ 1.],
         [ 1.],
         [ 1.]],

        [[ 2.],
         [ 2.],
         [ 2.]]])


In [5]:
a = torch.ensor([[1,10,5],[3,4,6]])
k = torch.max(a, 1)
print k[1]

AttributeError: 'module' object has no attribute 'ensor'

In [ ]:
print torch.LongTensor
a = [[2]*5]
print a
print torch.LongTensor(a).permute(1,0)
a.append([3]*5)
print torch.LongTensor(a).permute(1,0).shape



In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,0],[0,1]]);
a == 0

In [7]:
nn.Linear((2,2))

TypeError: __init__() takes at least 3 arguments (2 given)

In [56]:
from torch.nn.utils.rnn import pack_padded_sequence
a = torch.Tensor([1,2,0])
b = torch.Tensor([2,0,0])
# print a;
# print b;
c = [a, b]
d = torch.cat(c)
d= d.view(2,3)
# print d
# pad = nn.ConstantPad2d((0, 3, 0, 0), 0)
# pad(d)


print d
p = pack_padded_sequence(d, [2,1], batch_first=True)
print p[0]

tensor([[ 1.,  2.,  0.],
        [ 2.,  0.,  0.]])
tensor([ 1.,  2.,  2.])


In [37]:
lin = nn.Linear(10,5)
lin(torch.ones((2,2,10)))

RuntimeError: size mismatch, m1: [4 x 5], m2: [10 x 5] at /Users/soumith/minicondabuild3/conda-bld/pytorch_1524587833086/work/aten/src/TH/generic/THTensorMath.c:2033

In [51]:
rnn = nn.LSTMCell(10, 20)
input = torch.randn(6, 3, 10)
hx = torch.randn(3, 20)
cx = torch.randn(3, 20)
output = []
for i in range(6):
    hx, cx = rnn(input[i], (hx, cx))
    print hx
    output.append(hx)

tensor([[-0.0937, -0.4152, -0.3878, -0.0381,  0.0701,  0.2543,  0.0421,
         -0.2882,  0.2461,  0.0185, -0.1538, -0.0595,  0.4648, -0.4311,
          0.4542, -0.5407, -0.1600, -0.2503,  0.3507,  0.1312],
        [-0.2614,  0.2839,  0.0587,  0.2826,  0.2533, -0.2470, -0.2364,
          0.0000, -0.0872, -0.0372,  0.0163, -0.0026, -0.1796,  0.2320,
          0.0879, -0.0894,  0.1247,  0.1188,  0.2327, -0.4107],
        [ 0.1628,  0.1558,  0.0810, -0.0965, -0.1226,  0.0772,  0.1181,
          0.0451,  0.1111,  0.0025,  0.6456,  0.0857, -0.3449, -0.0136,
         -0.4903, -0.3808, -0.5094, -0.6081,  0.3369, -0.0570]])
tensor([[-0.1468, -0.2558, -0.0722,  0.0437,  0.0083,  0.3352, -0.0410,
         -0.2019,  0.1008, -0.0994, -0.2410, -0.1242,  0.2235, -0.0717,
          0.4086, -0.1755, -0.0915, -0.3064,  0.1193,  0.0406],
        [-0.1289,  0.2011,  0.0329,  0.0762,  0.3608,  0.0329, -0.3407,
         -0.0280, -0.1587,  0.0105,  0.0979,  0.0483, -0.1269,  0.0795,
         -0.0097, -0.24

In [45]:
print output

[tensor([[ 0.0008, -0.2089,  0.0966, -0.1651,  0.2627,  0.0346, -0.0783,
         -0.0905, -0.0033, -0.0517, -0.0245, -0.2322, -0.2592,  0.2088,
          0.0805,  0.4692, -0.0764, -0.0229, -0.2737,  0.1096],
        [-0.0031,  0.1830,  0.0601, -0.3145,  0.0753, -0.0486, -0.0985,
         -0.2938, -0.3305, -0.1643,  0.0111, -0.3854,  0.2234,  0.1723,
          0.0439,  0.0240,  0.1799,  0.0841, -0.3588,  0.2864],
        [ 0.4569, -0.3563, -0.0972, -0.6499,  0.4495, -0.5737, -0.1641,
         -0.3186,  0.2924, -0.1375,  0.1283, -0.6805,  0.0052,  0.1608,
          0.6188,  0.0614,  0.1541,  0.0447, -0.1431,  0.2494]]), tensor([[ 0.0098, -0.2167,  0.1034,  0.0078,  0.1166, -0.1862, -0.0687,
         -0.1902, -0.1562,  0.0212, -0.0588, -0.1849, -0.0533,  0.1473,
         -0.0486,  0.4164,  0.0630, -0.0878, -0.1822,  0.1624],
        [-0.2480,  0.0883,  0.4933, -0.1493,  0.0419, -0.0008, -0.0425,
         -0.0309, -0.1494, -0.0466, -0.2064, -0.4090,  0.0157,  0.3085,
          0.1768,  0.

In [69]:
a = torch.arange(2*3).view((2,3))
b = torch.arange(2*3).view((2,3))
print [a,b] # 2,2,3
c = torch.cat([a,b])
print c
print c.view((2,2,3))


[tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]]), tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]])]
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 0.,  1.,  2.],
        [ 3.,  4.,  5.]])
tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]]])
