In [1]:
import torch
from torch import nn
from torch.autograd import Variable
from torch import *

In [2]:
torch.int32

torch.int32

In [3]:
a = torch.ones((3,5,2,2))
b = torch.arange(3*5*2*2).view((3,5,2,2))
print b[0,0]
c = b.view((3,5,4));
d = c.permute(0,2,1)
# print c
print d.shape
a = torch.mean(d, 1)
print a.shape
f = a.unsqueeze(1);
(n,_,_) = f.shape
print n
# print d.contiguous().view((12, 5)).shape

print nn.Softmax
softmax = nn.Softmax()
print softmax(f);

tensor([[ 0.,  1.],
        [ 2.,  3.]])
torch.Size([3, 4, 5])
torch.Size([3, 5])
3
<class 'torch.nn.modules.activation.Softmax'>
tensor([[[ 4.2484e-18,  4.2484e-18,  4.2484e-18,  4.2484e-18,  4.2484e-18]],

        [[ 2.0612e-09,  2.0612e-09,  2.0612e-09,  2.0612e-09,  2.0612e-09]],

        [[ 1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00]]])


/Users/nsimsiri/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:17: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.


In [4]:
a = torch.arange(2*3*4).view((2,3,4))
b = torch.Tensor(([[1,1,1],[2,2,2]]));

print a
print b
print b.unsqueeze(2)


tensor([[[  0.,   1.,   2.,   3.],
         [  4.,   5.,   6.,   7.],
         [  8.,   9.,  10.,  11.]],

        [[ 12.,  13.,  14.,  15.],
         [ 16.,  17.,  18.,  19.],
         [ 20.,  21.,  22.,  23.]]])
tensor([[ 1.,  1.,  1.],
        [ 2.,  2.,  2.]])
tensor([[[ 1.],
         [ 1.],
         [ 1.]],

        [[ 2.],
         [ 2.],
         [ 2.]]])


In [5]:
a = torch.Tensor([[1,10,5],[3,4,6]])
k = torch.max(a, 1)
print k[1]

tensor([ 1,  2])


In [6]:
print torch.LongTensor
a = [[2]*5]
print a
print torch.LongTensor(a).permute(1,0)
a.append([3]*5)
print torch.LongTensor(a).permute(1,0).shape



<type 'torch.LongTensor'>
[[2, 2, 2, 2, 2]]
tensor([[ 2],
        [ 2],
        [ 2],
        [ 2],
        [ 2]])
torch.Size([5, 2])


In [7]:
import numpy as np

In [8]:
a = np.array([[1,0],[0,1]]);
a == 0

array([[False,  True],
       [ True, False]])

In [9]:
nn.Linear((2,2))

TypeError: __init__() takes at least 3 arguments (2 given)

In [ ]:
from torch.nn.utils.rnn import pack_padded_sequence
a = torch.Tensor([1,2,0])
b = torch.Tensor([2,0,0])
# print a;
# print b;
c = [a, b]
d = torch.cat(c)
d= d.view(2,3)
# print d
# pad = nn.ConstantPad2d((0, 3, 0, 0), 0)
# pad(d)


print d
p = pack_padded_sequence(d, [2,1], batch_first=True)
print p[0]

In [ ]:
lin = nn.Linear(10,5)
lin(torch.ones((2,2,10)))

In [ ]:
rnn = nn.LSTMCell(10, 20)
input = torch.randn(6, 3, 10)
hx = torch.randn(3, 20)
cx = torch.randn(3, 20)
output = []
for i in range(6):
    hx, cx = rnn(input[i], (hx, cx))
    print hx
    output.append(hx)

In [ ]:
print output

In [ ]:
a = torch.arange(2*3).view((2,3))
b = torch.arange(2*3).view((2,3))
print [a,b] # 2,2,3
c = torch.cat([a,b])
print c
print c.view((2,2,3))


In [ ]:
from torch.autograd import Variable

In [ ]:
x = Variable(torch.ones((1,1)))

In [39]:
t = torch.tensor([[1,2],[3,4],[5,6]])
print t
idx = torch.tensor([[2,0]])
torch.gather(t, 0, torch.tensor(idx))


tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6]])


tensor([[ 5,  2]])

In [128]:
captions = torch.tensor([[2,3,0,0],[2,0,0,0]])
length = torch.tensor([2,1])
print length
print captions
x = torch.arange(captions.size(0),dtype=torch.int64)
captions[x, length] = torch.tensor([9, 9])
print captions
front = torch.full((2,1), 1, dtype=torch.int64)
torch.cat((front,captions), 1)

tensor([ 2,  1])
tensor([[ 2,  3,  0,  0],
        [ 2,  0,  0,  0]])
tensor([[ 2,  3,  9,  0],
        [ 2,  9,  0,  0]])


tensor([[ 1,  2,  3,  9,  0],
        [ 1,  2,  9,  0,  0]])

In [55]:
import numpy as np

In [98]:
torch.int64


torch.int64