In [1]:
import torch
from torch import nn
from torch.autograd import Variable
from torch import *

In [2]:
torch.int32

torch.int32

In [3]:
a = torch.ones((3,5,2,2))
b = torch.arange(3*5*2*2).view((3,5,2,2))
print b[0,0]
c = b.view((3,5,4));
d = c.permute(0,2,1)
# print c
print d.shape
a = torch.mean(d, 1)
print a.shape
f = a.unsqueeze(1);
(n,_,_) = f.shape
print n
# print d.contiguous().view((12, 5)).shape

print nn.Softmax
softmax = nn.Softmax()
print softmax(f);

tensor([[ 0.,  1.],
        [ 2.,  3.]])
torch.Size([3, 4, 5])
torch.Size([3, 5])
3
<class 'torch.nn.modules.activation.Softmax'>
tensor([[[ 4.2484e-18,  4.2484e-18,  4.2484e-18,  4.2484e-18,  4.2484e-18]],

        [[ 2.0612e-09,  2.0612e-09,  2.0612e-09,  2.0612e-09,  2.0612e-09]],

        [[ 1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00]]])


/Users/nsimsiri/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:17: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.


In [4]:
a = torch.arange(2*3*4).view((2,3,4))
b = torch.Tensor(([[1,1,1],[2,2,2]]));

print a
print b
print b.unsqueeze(2)


tensor([[[  0.,   1.,   2.,   3.],
         [  4.,   5.,   6.,   7.],
         [  8.,   9.,  10.,  11.]],

        [[ 12.,  13.,  14.,  15.],
         [ 16.,  17.,  18.,  19.],
         [ 20.,  21.,  22.,  23.]]])
tensor([[ 1.,  1.,  1.],
        [ 2.,  2.,  2.]])
tensor([[[ 1.],
         [ 1.],
         [ 1.]],

        [[ 2.],
         [ 2.],
         [ 2.]]])


In [5]:
a = torch.ensor([[1,10,5],[3,4,6]])
k = torch.max(a, 1)
print k[1]

AttributeError: 'module' object has no attribute 'ensor'

In [ ]:
print torch.LongTensor
a = [[2]*5]
print a
print torch.LongTensor(a).permute(1,0)
a.append([3]*5)
print torch.LongTensor(a).permute(1,0).shape



In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,0],[0,1]]);
a == 0

In [7]:
nn.Linear((2,2))

TypeError: __init__() takes at least 3 arguments (2 given)

In [31]:
a = torch.Tensor([1,2,0])
b = torch.Tensor([2,0,0])
print a;
print b;
c = [a, b]
d = torch.cat(c)
d= d.view(2,3)
print d
pad = nn.ConstantPad2d((0, 3, 0, 0), 0)
pad(d)


tensor([ 1.,  2.,  0.])
tensor([ 2.,  0.,  0.])
tensor([[ 1.,  2.,  0.],
        [ 2.,  0.,  0.]])


tensor([[ 1.,  2.,  0.,  0.,  0.,  0.],
        [ 2.,  0.,  0.,  0.,  0.,  0.]])

In [37]:
lin = nn.Linear(10,5)
lin(torch.ones((2,2,10)))

RuntimeError: size mismatch, m1: [4 x 5], m2: [10 x 5] at /Users/soumith/minicondabuild3/conda-bld/pytorch_1524587833086/work/aten/src/TH/generic/THTensorMath.c:2033