In [1]:
import numpy as np


In [23]:
x = np.random.random((5,5))
print(x)
y = np.expand_dims(x, (2))
print(y.shape)


y = np.zeros((x.shape[0], x.shape[1], 3))
y[:,:,0] = x
print(y)

[[0.11961632 0.75107761 0.51553375 0.76917322 0.0849884 ]
 [0.17528621 0.22874884 0.68978554 0.37709092 0.17092276]
 [0.88416685 0.30723245 0.4944694  0.55223031 0.14075619]
 [0.57478203 0.23498152 0.74634653 0.32231685 0.6491111 ]
 [0.98411235 0.34354572 0.09675898 0.67863458 0.68358639]]
(5, 5, 1)
[[[0.11961632 0.         0.        ]
  [0.75107761 0.         0.        ]
  [0.51553375 0.         0.        ]
  [0.76917322 0.         0.        ]
  [0.0849884  0.         0.        ]]

 [[0.17528621 0.         0.        ]
  [0.22874884 0.         0.        ]
  [0.68978554 0.         0.        ]
  [0.37709092 0.         0.        ]
  [0.17092276 0.         0.        ]]

 [[0.88416685 0.         0.        ]
  [0.30723245 0.         0.        ]
  [0.4944694  0.         0.        ]
  [0.55223031 0.         0.        ]
  [0.14075619 0.         0.        ]]

 [[0.57478203 0.         0.        ]
  [0.23498152 0.         0.        ]
  [0.74634653 0.         0.        ]
  [0.32231685 0.         0.

In [18]:
print(np.zeros_like(y))

[[[0.]
  [0.]
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  [0.]
  [0.]]]
